someAsyncFunction().catch((error) => {
    // Non fare nulla o loggare l'errore silenziosamente
    console.log('Errore silenziato:', error);
});